### ISSUE TITLE
Dynamic reconfigure

### ISSUE THREAD

**Issue by lucasw** [lucasw/imgui_ros#9]
Created number/text/enum selection boxes out of the Config.  I think this isn't too hard in C++.

Use the number boxes where clicking and dragging left or right changes the value.

**Comment by lucasw** [comment]
Revive this again for ros1.

**Comment by lucasw** [comment]
Need a refreshable combo box that lists all known dr servers, also allow manual editing of the text.

**Comment by lucasw** [comment]
Need to be able to handle hung up servers when making a service call.

**Comment by lucasw** [comment]
Seeing an error like in ros/dynamic_reconfigure#109 when I try to reconfigure the rospy server with the imgui client

```
[[/example_server_node2] [/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py]:[578] [Error processing request: 'list' object has no attribute 'items'
['Traceback (most recent call last):\n', '  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 629, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/server.py", line 135, in _set_callback\n    return encode_config(self.update_configuration(decode_config(req.config, self.type.config_description)))\n', '  File "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/encoding.py", line 312, in decode_config\n    add_params(d[\'groups\'], description)\n', '  File "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/encoding.py", line 308, in add_params\n    for _nr, dr in descr[\'groups\'].items():\n', "AttributeError: 'list' object has no attribute 'items'\n"]]
```

Same error on multiple lines:
```
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 629, in _handle_request
    response = convert_return_to_response(self.handler(request), self.response_class)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/server.py", line 135, in _set_callback
    return encode_config(self.update_configuration(decode_config(req.config, self.type.config_description)))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/encoding.py", line 312, in decode_config
    add_params(d[\'groups\'], description)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/encoding.py", line 308, in add_params
    for _nr, dr in descr[\'groups\'].items():

AttributeError: 'list' object has no attribute 'items'
```

https://answers.ros.org/question/292016/using-groups-with-dynamic_reconfigure-rqt_reconfigure/

**Comment by lucasw** [comment]
When I compare the output of parameter_description for the roscpp server and the rospy one I see differences.

The first is the order of the groups is different, the other that seems to be the cause of the problem is that roscpp has `groups:` entries for max and min and dflt, while the rospy one is empty.

```
  groups: 
    - 
      name: "Default"
      state: True
      id: 0
      parent: 0
    - 
      name: "Sub"
      state: True
      id: 1
      parent: 0
```

**Comment by lucasw** [comment]
Look at the the service call from rqt reconfigure as received by the python server.

Make a custom server that doesn't get wrapped, but takes a dynamic reconfigure request directly.

**Comment by lucasw** [comment]
```
[ERROR] 1573425455.744536870 /home/lucasw/catkin_ws/devel/.private/dynamic_reconfigure_example/include/dynamic_reconfigure_example/ExampleConfig.h:362: ExampleConfig::__fromMessage__ called with an unexpected parameter.
[ERROR] 1573425455.744771956 /home/lucasw/catkin_ws/devel/.private/dynamic_reconfigure_example/include/dynamic_reconfigure_example/ExampleConfig.h:363: Booleans:
[ERROR] 1573425455.744820503 /home/lucasw/catkin_ws/devel/.private/dynamic_reconfigure_example/include/dynamic_reconfigure_example/ExampleConfig.h:366: Integers:
[ERROR] 1573425455.744858887 /home/lucasw/catkin_ws/devel/.private/dynamic_reconfigure_example/include/dynamic_reconfigure_example/ExampleConfig.h:369: Doubles:
[ERROR] 1573425455.744907920 /home/lucasw/catkin_ws/devel/.private/dynamic_reconfigure_example/include/dynamic_reconfigure_example/ExampleConfig.h:371:   small_double
[ERROR] 1573425455.744988821 /home/lucasw/catkin_ws/devel/.private/dynamic_reconfigure_example/include/dynamic_reconfigure_example/ExampleConfig.h:371:   small_double
[ERROR] 1573425455.745067203 /home/lucasw/catkin_ws/devel/.private/dynamic_reconfigure_example/include/dynamic_reconfigure_example/ExampleConfig.h:372: Strings:
```

```
      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("ExampleConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");

```

The same parameter is getting pushed into the message when the slider is updated quickly - need to have an intermediate data structure that gets overwritten instead of appending.
